<?php

namespace Container05bTVvP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KQehNsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._KQehNs' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._KQehNs'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'aboutRepository' => ['privates', 'App\\Repository\\AboutRepository', 'getAboutRepositoryService', true],
            'jobRepository' => ['privates', 'App\\Repository\\JobRepository', 'getJobRepositoryService', true],
            'schoolRepository' => ['privates', 'App\\Repository\\SchoolRepository', 'getSchoolRepositoryService', true],
        ], [
            'aboutRepository' => 'App\\Repository\\AboutRepository',
            'jobRepository' => 'App\\Repository\\JobRepository',
            'schoolRepository' => 'App\\Repository\\SchoolRepository',
        ]);
    }
}
