<?php

namespace ContainerXZiPQSI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_W7kT9_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._w7kT9.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._w7kT9.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\Admin\\AboutController::browse' => ['privates', '.service_locator.dZBTC_j', 'get_ServiceLocator_DZBTCJService', true],
            'App\\Controller\\Admin\\AboutController::edit' => ['privates', '.service_locator.bwXeLQs', 'get_ServiceLocator_BwXeLQsService', true],
            'App\\Controller\\Admin\\JobController::browse' => ['privates', '.service_locator.KkRJk_2', 'get_ServiceLocator_KkRJk2Service', true],
            'App\\Controller\\Admin\\JobController::delete' => ['privates', '.service_locator.O64cWSR', 'get_ServiceLocator_O64cWSRService', true],
            'App\\Controller\\Admin\\JobController::edit' => ['privates', '.service_locator.O64cWSR', 'get_ServiceLocator_O64cWSRService', true],
            'App\\Controller\\Admin\\ProjectController::browse' => ['privates', '.service_locator.mbtGKvu', 'get_ServiceLocator_MbtGKvuService', true],
            'App\\Controller\\Admin\\ProjectController::delete' => ['privates', '.service_locator.bU8nL9L', 'get_ServiceLocator_BU8nL9LService', true],
            'App\\Controller\\Admin\\ProjectController::edit' => ['privates', '.service_locator.mbtGKvu', 'get_ServiceLocator_MbtGKvuService', true],
            'App\\Controller\\Admin\\SchoolController::delete' => ['privates', '.service_locator.2u1cZkh', 'get_ServiceLocator_2u1cZkhService', true],
            'App\\Controller\\Admin\\SchoolController::edit' => ['privates', '.service_locator.2u1cZkh', 'get_ServiceLocator_2u1cZkhService', true],
            'App\\Controller\\Admin\\TagController::browse' => ['privates', '.service_locator.V.8Df87', 'get_ServiceLocator_V_8Df87Service', true],
            'App\\Controller\\Admin\\TagController::delete' => ['privates', '.service_locator.9vvZCTm', 'get_ServiceLocator_9vvZCTmService', true],
            'App\\Controller\\Admin\\TagController::edit' => ['privates', '.service_locator.9vvZCTm', 'get_ServiceLocator_9vvZCTmService', true],
            'App\\Controller\\Admin\\TypeController::browse' => ['privates', '.service_locator.KkRJk_2', 'get_ServiceLocator_KkRJk2Service', true],
            'App\\Controller\\ProjectController::browse' => ['privates', '.service_locator.TatKeTZ', 'get_ServiceLocator_TatKeTZService', true],
            'App\\Controller\\ProjectController::browseByTag' => ['privates', '.service_locator.V.8Df87', 'get_ServiceLocator_V_8Df87Service', true],
            'App\\Controller\\ProjectController::browseByType' => ['privates', '.service_locator.TatKeTZ', 'get_ServiceLocator_TatKeTZService', true],
            'App\\Controller\\ProjectController::read' => ['privates', '.service_locator.GvdJjkI', 'get_ServiceLocator_GvdJjkIService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.xA8Fw_.', 'get_ServiceLocator_XA8Fw_Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\Admin\\AboutController:browse' => ['privates', '.service_locator.dZBTC_j', 'get_ServiceLocator_DZBTCJService', true],
            'App\\Controller\\Admin\\AboutController:edit' => ['privates', '.service_locator.bwXeLQs', 'get_ServiceLocator_BwXeLQsService', true],
            'App\\Controller\\Admin\\JobController:browse' => ['privates', '.service_locator.KkRJk_2', 'get_ServiceLocator_KkRJk2Service', true],
            'App\\Controller\\Admin\\JobController:delete' => ['privates', '.service_locator.O64cWSR', 'get_ServiceLocator_O64cWSRService', true],
            'App\\Controller\\Admin\\JobController:edit' => ['privates', '.service_locator.O64cWSR', 'get_ServiceLocator_O64cWSRService', true],
            'App\\Controller\\Admin\\ProjectController:browse' => ['privates', '.service_locator.mbtGKvu', 'get_ServiceLocator_MbtGKvuService', true],
            'App\\Controller\\Admin\\ProjectController:delete' => ['privates', '.service_locator.bU8nL9L', 'get_ServiceLocator_BU8nL9LService', true],
            'App\\Controller\\Admin\\ProjectController:edit' => ['privates', '.service_locator.mbtGKvu', 'get_ServiceLocator_MbtGKvuService', true],
            'App\\Controller\\Admin\\SchoolController:delete' => ['privates', '.service_locator.2u1cZkh', 'get_ServiceLocator_2u1cZkhService', true],
            'App\\Controller\\Admin\\SchoolController:edit' => ['privates', '.service_locator.2u1cZkh', 'get_ServiceLocator_2u1cZkhService', true],
            'App\\Controller\\Admin\\TagController:browse' => ['privates', '.service_locator.V.8Df87', 'get_ServiceLocator_V_8Df87Service', true],
            'App\\Controller\\Admin\\TagController:delete' => ['privates', '.service_locator.9vvZCTm', 'get_ServiceLocator_9vvZCTmService', true],
            'App\\Controller\\Admin\\TagController:edit' => ['privates', '.service_locator.9vvZCTm', 'get_ServiceLocator_9vvZCTmService', true],
            'App\\Controller\\Admin\\TypeController:browse' => ['privates', '.service_locator.KkRJk_2', 'get_ServiceLocator_KkRJk2Service', true],
            'App\\Controller\\ProjectController:browse' => ['privates', '.service_locator.TatKeTZ', 'get_ServiceLocator_TatKeTZService', true],
            'App\\Controller\\ProjectController:browseByTag' => ['privates', '.service_locator.V.8Df87', 'get_ServiceLocator_V_8Df87Service', true],
            'App\\Controller\\ProjectController:browseByType' => ['privates', '.service_locator.TatKeTZ', 'get_ServiceLocator_TatKeTZService', true],
            'App\\Controller\\ProjectController:read' => ['privates', '.service_locator.GvdJjkI', 'get_ServiceLocator_GvdJjkIService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.xA8Fw_.', 'get_ServiceLocator_XA8Fw_Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\Admin\\AboutController::browse' => '?',
            'App\\Controller\\Admin\\AboutController::edit' => '?',
            'App\\Controller\\Admin\\JobController::browse' => '?',
            'App\\Controller\\Admin\\JobController::delete' => '?',
            'App\\Controller\\Admin\\JobController::edit' => '?',
            'App\\Controller\\Admin\\ProjectController::browse' => '?',
            'App\\Controller\\Admin\\ProjectController::delete' => '?',
            'App\\Controller\\Admin\\ProjectController::edit' => '?',
            'App\\Controller\\Admin\\SchoolController::delete' => '?',
            'App\\Controller\\Admin\\SchoolController::edit' => '?',
            'App\\Controller\\Admin\\TagController::browse' => '?',
            'App\\Controller\\Admin\\TagController::delete' => '?',
            'App\\Controller\\Admin\\TagController::edit' => '?',
            'App\\Controller\\Admin\\TypeController::browse' => '?',
            'App\\Controller\\ProjectController::browse' => '?',
            'App\\Controller\\ProjectController::browseByTag' => '?',
            'App\\Controller\\ProjectController::browseByType' => '?',
            'App\\Controller\\ProjectController::read' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\Admin\\AboutController:browse' => '?',
            'App\\Controller\\Admin\\AboutController:edit' => '?',
            'App\\Controller\\Admin\\JobController:browse' => '?',
            'App\\Controller\\Admin\\JobController:delete' => '?',
            'App\\Controller\\Admin\\JobController:edit' => '?',
            'App\\Controller\\Admin\\ProjectController:browse' => '?',
            'App\\Controller\\Admin\\ProjectController:delete' => '?',
            'App\\Controller\\Admin\\ProjectController:edit' => '?',
            'App\\Controller\\Admin\\SchoolController:delete' => '?',
            'App\\Controller\\Admin\\SchoolController:edit' => '?',
            'App\\Controller\\Admin\\TagController:browse' => '?',
            'App\\Controller\\Admin\\TagController:delete' => '?',
            'App\\Controller\\Admin\\TagController:edit' => '?',
            'App\\Controller\\Admin\\TypeController:browse' => '?',
            'App\\Controller\\ProjectController:browse' => '?',
            'App\\Controller\\ProjectController:browseByTag' => '?',
            'App\\Controller\\ProjectController:browseByType' => '?',
            'App\\Controller\\ProjectController:read' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
