<?php

namespace ContainerXZiPQSI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2u1cZkhService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2u1cZkh' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2u1cZkh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'school' => ['privates', '.errored..service_locator.2u1cZkh.App\\Entity\\School', NULL, 'Cannot autowire service ".service_locator.2u1cZkh": it references class "App\\Entity\\School" but no such service exists.'],
        ], [
            'school' => 'App\\Entity\\School',
        ]);
    }
}
