<?php

namespace ContainerXZiPQSI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSchoolService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.2u1cZkh.App\Entity\School' shared service.
     *
     * @return \App\Entity\School
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.2u1cZkh": it references class "App\\Entity\\School" but no such service exists.');
    }
}
