<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container05bTVvP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container05bTVvP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container05bTVvP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container05bTVvP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container05bTVvP\App_KernelDevDebugContainer([
    'container.build_hash' => '05bTVvP',
    'container.build_id' => 'edf039f2',
    'container.build_time' => 1602238102,
], __DIR__.\DIRECTORY_SEPARATOR.'Container05bTVvP');
